#!/bin/bash
set -e

if [ "$#" -ne 1 ]; then
  echo "Usage: ./scripts/showresult <result_file>"
  exit 1
fi

RESULT_FILE="$1"

if [ ! -f "$RESULT_FILE" ]; then
  echo "File not found: $RESULT_FILE"
  exit 1
fi

sed -n '1,120p' "$RESULT_FILE"
